### ISSUE TITLE
Problem using activeset 0.6.2

### ISSUE THREAD

**Issue by barendt** [fractaledmind/actionset#12]
I updated the bundle in CVPF to use activeset 0.6.2 and actionset 0.4.0 and got an error:
![error](https://user-images.githubusercontent.com/227431/44548745-f6541b80-a6ec-11e8-9598-7a12c83cdee8.png)

I can't quite tell what all changed in ActiveSet, but it looks like this might be a place where ActionSet needs a corresponding update.

**Comment by fractaledmind** [comment]
Ah. It appears I missed a spot in the `0.4.0` upgrade to work with the new ActiveSet. I'll get that fixed in the next couple of days.
