### ISSUE TITLE
Cannot authorize (implied) Pundit Policy When Using EnumerableStrategy 

### ISSUE THREAD

**Issue by RaymondFallon** [fractaledmind/actionset#72]
Howdy!

I ran into what I believe is a bug. I am using `sort_set` in my controller and it has been working fine, so long as I've been sorting by DB columns:

```ruby
module Sms
  class PatientsController < ApplicationController
    def index
      authorize @patients = sort_set(Patient.includes(:associated_things))
    end

    ...
```
Notice that I am using Pundit's `authorize` directly on the ActiveSet that is returned. This became a problem when I started trying to sort by an instance method of the `Patient` class. In that case I was seeing this error:

`unable to find policy 'ActiveSetPolicy' for '#<ActiveSet:70216639644980 @instructions={:sort=>{:last_message_time=>"asc"}}>`

I don't have a clear picture of the internals of how ActiveSet and Pundit interact, but my guess is something like the following is happening:
When ActionSet uses the ActiveRecordStrategy to sort, Pundit is handed an ActiveRecordCollection of my Patient class and knows which Policy to use.
When ActionSet has to use the EnumerableStategy, Pundit is handed a vanilla Array object and doesn’t know which Policy to use and ends up looking for a not-to-be-found elusive ActiveSetPolicy.

Now, in my case, it’s no problem to split this one line into two:

```ruby
module Sms
  class PatientsController < ApplicationController
    def index
      authorize Patient
      @patients = sort_set(Patient.includes(:associated_things))
    end

    ...
```

Not sure if you consider this a bug, but I figured I would bring it to your attention. Hope life is tolerable-to-good right now in Berlin! 

Versions:
```
rails (5.2.4.2)
ruby. 2.6.5
actionset (0.9.2)
pg (1.1.4)
```

**Comment by riyengar8** [comment]
Hi @RaymondFallon . FWIW, I would definitely split the authorize call onto its own line in the example you give above. I don't think this is a bug in ActionSet so much as a limitation of the Policy finders in Pundit.

A couple of other points that may or may not be of interest:

* Pundit lets you pass a clue for `authorize` to tell it how to find the policy class in cases where its magic will not return the right result:

```ruby
authorize @some_set_of_patients, policy_class: PatientPolicy
```

* For an index route, there's usually no need to call authorize against a set. The nature of index routes is usually such that a user is either allowed to index the resource or not, and the index returned is filtered by the user's scope. So perhaps a more common way to approach your example could be:

```ruby
def index
  # Can this user index patients at all?
  authorize Patient

  # return only those patients that this user is allowed to see as defined in the PatientPolicy::Scope
  @patients = sort_set(policy_scope(Patient.includes(:associated_things)))
end
```
 
See https://github.com/varvet/pundit#scopes for more detail.

**Comment by RaymondFallon** [comment]
Thanks @riyengar8! That all makes sense. The explicit `policy_class` sounds like the right tool in this case, and I think I'll go with that. Looks like I'll have to work a little harder to find a real bug and have a chance to say hi to @fractaledmind!

**Comment by fractaledmind** [comment]
Well thought-thru all around. Looking forward to the real bug you do find :)
